class ErrorCode:
    UNKNOWN = "ERR_000"
    POST_ALREADY_LIKED = "ERR_101"
    POST_NOT_LIKED = "ERR_102"
    POST_NOT_FOUND = "ERR_103"
    COMMENT_NOT_FOUND = "ERR_104"
    UNAUTHORIZED = "ERR_105"