class ErrorCode:
    UNKNOWN = "ERR_000"
    INVALID_VERIFICATION_CODE = "ERR_001"
    VERIFICATION_CODE_EXPIRED = "ERR_002"
    USER_BLOCKED = "ERR_003"
    USER_NOT_FOUND = "ERR_004"
    SELF_FOLLOW = "ERR_005"
    ALREADY_FOLLOWED = "ERR_006"
    NOT_FOLLOWING = "ERR_007"
